repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        # Убираем "-r ." так как pre-commit сам передает файлы.
        # Используем exclude от pre-commit вместо "-x tests" от bandit.
        args: ["-ll"]
        exclude: ^tests/