version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_job_bot
    restart: always
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/jobs_database.db
      - LOG_FILE=/app/logs/bot.json.log
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8000:8000"  # Prometheus metrics
